export enum Region {
  US_EAST_VIRGINIA = 'us-east-1',
  US_EAST_OHIO = 'us-east-2',
  US_WEST_NORTH_CALIFORNIA = 'us-west-1',
  US_WEST_OREGON = 'us-west-2',
  AFRICA_CAPE_TOWN = 'af-south-1',
  ASIA_HONG_KONG = 'ap-east-1',
  ASIA_TOKYO = 'ap-northeast-1',
  ASIA_SEOUL = 'ap-northeast-2',
  ASIA_MUMBAI = 'ap-south-1',
  ASIA_SINGAPORE = 'ap-southeast-1',
  ASIA_SYDNEY = 'ap-southeast-2',
  CANADA_CENTRAL = 'ca-central-1',
  EUROPE_FRANKFURT = 'eu-central-1',
  EUROPE_IRELAND = 'eu-west-1',
  EUROPE_LONDON = 'eu-west-2',
  EUROPE_PARIS = 'eu-west-3',
  EUROPE_STOCKHOLM = 'eu-north-1',
  MIDDLE_EAST_BAHRAIN = 'me-south-1',
  SOUTH_AMERICA_SA_PAULO = 'sa-east-1',
}
